obstacle_range: 1.0
raytrace_range: 0.8
footprint: [[-0.1,0.08], [-0.1,-0.08], [0.1,-0.08], [0.1,0.08]] #check and edit
#robot_radius: 0.3

inflation_radius: 0.09
cost_scaling_factor: 0.09

observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor:  {
                    sensor_frame: laser_frame, 
                    data_type: LaserScan, 
                    topic: /scan, 
                    marking: true, 
                    clearing: true
                    }

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}